config/routes.rb
Rails.application.routes.draw do
  get	 'welcome/index'  

  root	'welcome#index'

  resources  :articles

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many  :items    

end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render  'edit'
    end    
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<div class="container-fluid col-md-4 text-md-center">
    <%= link_to 'New article', new_article_path, class:  "btn btn-primary" %>
    <h1>All Articles</h1>

    <table class="table">
        <tr>
            <th scope="col">Id</th>
            <th cope="col">Title</th>
            <th scope="col">Text</th>
            <th></th>
        </tr>

        <% @articles.each do |article| %>
        <tr>
            <th scope="row"><%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article), class:  "btn btn-dark" %></td>
        </tr>
        <% end %>
    </table>
    <div>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'articles', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="container-fluid col-md-4">
        <%= form_with scope: :article,url: articles_path, local: true do |form| %>
        <% if @article.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
            <h2>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                <li class="text-danger"><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <p>
            <%= form.label :title %><br>
            <%= form.text_field :title, class: 'form-control' %>
        </p>

        <p>
            <%= form.label :text %><br>
            <%= form.text_area :text, class: 'form-control' %>
        </p>

        <p>
            <%= form.submit :Submit, class: 'btn btn-dark' %>
        </p>
        <% end %>
        <%= link_to 'Back', articles_path %>
    </div>
</body>

</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'articles', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="container ">
        <div class="row">
            <div class="col-md-4 m-3">
                <div class="card">

                    <div class="card-header">
                        <strong>Id:</strong>
                        <%= @article.id %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> <%= @article.title %>
                        </h5>
                        <p class="card-text"> <%= @article.text %>
                        </p>
                        <%= link_to 'Back', articles_path, class:  "btn btn-info" %>

                    </div>
                </div>

            </div>
            <div class="col-md-4 m-3">
                <div class="card">
                    <div class="card-header">
                        <h5>Edit Article</h5>

                    </div>
                    <div class="card-body">


                        <%= form_with(model: @article, local: true) do |form| %>

                        <% if @article.errors.any? %>
                        <div id="error_explanation">
                            <h2>
                                <%= pluralize(@article.errors.count, "error") %> prohibited
                                this article from being saved:
                            </h2>
                            <ul>
                                <% @article.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>
                        <% end %>

                        <p>
                            <%= form.label :title %><br>
                            <%= form.text_field :title, class: 'form-control' %>
                        </p>

                        <p>
                            <%= form.label :text %><br>
                            <%= form.text_area :text, class: 'form-control' %>
                        </p>

                        <p>
                            <%= form.submit  :Update, class:  "btn btn-primary"%>
                            <%= link_to 'Back', articles_path, class: "btn btn-dark" %>

                        </p>

                        <% end %>


                    </div>
                </div>

            </div>
        </div>
    </div>

</body>

</html>

app/views/layouts/_footer.html.erb
 <footer class="page-footer font-small bg-secondary fixed-bottom">

     <!-- Copyright -->
     <div class="footer-copyright text-center text-light py-3">
         The Inventory Management
     </div>
     <!-- Copyright -->

 </footer>
 <!-- Footer -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>


        </ul>
        <a class="nav-link" href="#">Features</a>
        <%= link_to "My Blog", controller: 'articles' %>
    </div>

    </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
        <%= yield %>
</body>

</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Proj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> col-md-8 col-md-offset-2 main"> <%= value %> </div>
        <% end %>
        <h1>Hello Railssssss!</h1>
    <%= render 'layouts/footer' %>

</body>

</html>